services:
  app:
    build: .
    working_dir: /usr/src/vkserver
    volumes:
      - "/mnt/videoke/:/usr/src/vkserver/videos/"
      - "/etc/localtime:/etc/localtime:ro"
    container_name: app-vkserver
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9229:9229
    command: npm start
