version: '3'
services:
  app:
    build: .
    working_dir: /usr/src/vkserver
    volumes:
      - "/mnt/videoke/:/usr/src/vkserver/videos/"
    container_name: app-vkserver
    restart: always
    ports:
      - 8000:8000
      - 9229:9229
    command: npm start
