version: '3'
services:
  app:
    build: .
    volumes:
      - ./app/:/usr/src/app/
      - /mnt/videoke/:/app/videos/
    container_name: app-vkserver
    restart: always
    ports:
      - 8000:8000
      - 9229:9229
    command: npm start
